AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Forex Analytics Platform Template

Globals:
  Function:
    Timeout: 300

Parameters:
  ProjectApiKey:
    Type: String
    Description: Finnhub API Key
  TwitterConsumerKey:
    Type: String
  TwitterConsumerSecret:
    Type: String
  TwitterAccessTokenKey:
    Type: String
  TwitterAccessTokenSecret:
    Type: String

Resources:
    ForexDataWebsocket:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ForexDataWebsocket
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.message"
    ConnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $connect
        AuthorizationType: NONE
        OperationName: ConnectRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref ConnectIntegration
    ConnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    DisconnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $disconnect
        AuthorizationType: NONE
        OperationName: DisconnectRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref DisconnectIntegration
    DisconnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    SubscribeRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: subscribe
        AuthorizationType: NONE
        OperationName: SubscribeRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref SubscribeIntegration
    SubscribeIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    UnsubscribeRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: unsubscribe
        AuthorizationType: NONE
        OperationName: UnsubscribeRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref UnsubscribeIntegration
    UnsubscribeIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    DefaultRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref ForexDataWebsocket
        RouteKey: $default
        AuthorizationType: NONE
        OperationName: DefaultRoute
        Target: !Join
          - '/'
          - - 'integrations'
            - !Ref DefaultIntegration
    DefaultIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref ForexDataWebsocket
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketMessageFunction.Arn}/invocations
    Deployment:
      Type: AWS::ApiGatewayV2::Deployment
      DependsOn:
        - ConnectRoute
        - SubscribeRoute
        - UnsubscribeRoute
        - DisconnectRoute
        - DefaultRoute
      Properties:
        ApiId: !Ref ForexDataWebsocket
    Stage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        StageName: Prod
        DeploymentId: !Ref Deployment
        ApiId: !Ref ForexDataWebsocket

    SymbolDataFunction:
      Type: AWS::Serverless::Function
      Properties:
        MemorySize: 256
        PackageType: Image
        FunctionName: SymbolDataFunction
        Environment:
            Variables:
              PROJECT_API_KEY: !Ref ProjectApiKey
              API_GATEWAY_URI: !Sub 'https://${ForexDataWebsocket}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
        Events:
          ScheduledFinnhubCall1:
            Type: Schedule
            Properties:
              Schedule: cron(0/2 22-23 ? * SUN *)
          ScheduledFinnhubCall2:
            Type: Schedule
            Properties:
              Schedule: cron(0/2 * ? * MON-THU *)
          ScheduledFinnhubCall3:
            Type: Schedule
            Properties:
              Schedule: cron(0/2 0-22 ? * FRI *)
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref SymbolRateTable
          - DynamoDBCrudPolicy:
              TableName: !Ref WebsocketConnectionsTable
          - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForexDataWebsocket}/*'
      Metadata:
        DockerTag: go1.x-v1
        DockerContext: ./technical-analysis-lambda
        Dockerfile: Dockerfile

    WebsocketMessageFunction:
      Type: AWS::Serverless::Function
      Properties:
        PackageType: Image
        FunctionName: WebsocketMessageFunction
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref SymbolRateTable
          - DynamoDBCrudPolicy:
              TableName: !Ref WebsocketConnectionsTable
          - DynamoDBCrudPolicy:
              TableName: !Ref TechnicalAnalysisTable
          - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForexDataWebsocket}/*'
      Metadata:
        DockerTag: go1.x-v1
        DockerContext: ./websocket-server-lambda
        Dockerfile: Dockerfile
    WebsocketMessageFunctionPermission:
      Type: AWS::Lambda::Permission
      DependsOn:
        - ForexDataWebsocket
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref WebsocketMessageFunction
        Principal: apigateway.amazonaws.com

    PredictionFunction:
      Type: AWS::Serverless::Function
      Properties:
        MemorySize: 2048
        PackageType: Image
        FunctionName: PredictionFunction
        Environment:
            Variables:
              API_GATEWAY_URI: !Sub 'https://${ForexDataWebsocket}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
              TWITTER_CONSUMER_KEY: !Ref TwitterConsumerKey
              TWITTER_CONSUMER_SECRET: !Ref TwitterConsumerSecret
              TWITTER_ACCESS_TOKEN_KEY: !Ref TwitterAccessTokenKey
              TWITTER_ACCESS_TOKEN_SECRET: !Ref TwitterAccessTokenSecret
        Policies:
          - AWSLambdaDynamoDBExecutionRole
          - DynamoDBCrudPolicy:
              TableName: !Ref TechnicalAnalysisTable
          - DynamoDBCrudPolicy:
              TableName: !Ref WebsocketConnectionsTable
          - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ForexDataWebsocket}/*'
        Events:
          Stream:
            Type: DynamoDB
            Properties:
              Stream: !GetAtt SymbolRateTable.StreamArn
              StartingPosition: LATEST
      Metadata:
        DockerTag: python3.8
        DockerContext: ./prediction-lambda/handler
        Dockerfile: Dockerfile

    SymbolRateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SymbolRateTable
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    WebsocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WebsocketConnectionsTable
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    TechnicalAnalysisTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TechnicalAnalysisTable
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

Outputs:
  WebSocketURI:
    Value: !Join ['', ['wss://', !Ref ForexDataWebsocket, '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref 'Stage']]
